"""
Task Puller — polls the CF Worker for pending tasks assigned to this node,
executes them locally via the hand registry, and posts results back.
Logs all activity to ~/.agent-route/task_puller.log
"""
import os
import asyncio
import logging
from datetime import datetime
import httpx

from app.config import get_data_dir

_puller_task = None
POLL_INTERVAL = 5  # seconds

# File logger
_log_file = os.path.join(get_data_dir(), "task_puller.log")
_logger = logging.getLogger("task_puller")
_logger.setLevel(logging.DEBUG)
_fh = logging.FileHandler(_log_file, encoding="utf-8")
_fh.setFormatter(logging.Formatter("%(asctime)s | %(levelname)-5s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S"))
_logger.addHandler(_fh)


async def _pull_and_execute():
    """Pull pending tasks and execute them."""
    from app.hands.registry import hand_registry
    from app.config import get_workspaces_dir

    worker_url = os.getenv("CF_WORKER_URL", "")
    node_id = os.getenv("NODE_ID", "")
    auth_key = os.getenv("NODE_TOKEN", "") or os.getenv("CF_WORKER_API_KEY", "")

    if not worker_url or not node_id or not auth_key:
        return

    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.get(
                f"{worker_url}/api/nodes/{node_id}/tasks/pending",
                headers={"X-API-Key": auth_key},
            )
            if resp.status_code != 200:
                _logger.warning(f"Pull failed: HTTP {resp.status_code} — {resp.text[:200]}")
                return

            tasks = resp.json().get("tasks", [])
            if not tasks:
                return

            _logger.info(f"Pulled {len(tasks)} task(s)")

            for task in tasks:
                task_id = task["id"]
                hand_name = task["hand_name"]
                prompt = task["prompt"]
                session_id = task.get("session_id")
                start_time = datetime.now()

                _logger.info(f"EXEC {task_id[:12]} | hand={hand_name} | prompt={prompt[:80]}...")
                print(f"[task-puller] Executing {task_id[:8]} ({hand_name})")

                hand = hand_registry.get(hand_name)
                if not hand:
                    msg = f"Hand '{hand_name}' not registered"
                    _logger.error(f"FAIL {task_id[:12]} | {msg}")
                    print(f"[task-puller] {msg}")
                    await _post_result(client, worker_url, auth_key, task_id, 1, msg)
                    continue

                workspace_dir = os.path.join(get_workspaces_dir(), session_id or task_id)
                os.makedirs(workspace_dir, exist_ok=True)

                # Download workspace files from R2 (cross-node context transfer)
                await _sync_workspace_from_r2(client, worker_url, auth_key, session_id or task_id, workspace_dir)

                try:
                    result = await hand.execute(prompt, workspace_dir=workspace_dir)
                    exit_code = result.exit_code
                    output = result.output
                    elapsed = (datetime.now() - start_time).total_seconds()
                    _logger.info(f"DONE {task_id[:12]} | hand={hand_name} | exit={exit_code} | {elapsed:.1f}s | {len(output)} chars")
                    if exit_code != 0:
                        _logger.warning(f"FAIL {task_id[:12]} | output={output[:300]}")
                    print(f"[task-puller] Task {task_id[:8]} done (exit={exit_code}, {elapsed:.1f}s)")
                except Exception as e:
                    exit_code = 1
                    output = str(e)
                    elapsed = (datetime.now() - start_time).total_seconds()
                    _logger.error(f"ERROR {task_id[:12]} | hand={hand_name} | {elapsed:.1f}s | {e}")
                    print(f"[task-puller] Task {task_id[:8]} failed: {e}")

                await _post_result(client, worker_url, auth_key, task_id, exit_code, output)

                # Sync workspace files to R2
                from app.workspace_sync import sync_session_now
                await sync_session_now(session_id or task_id)

    except Exception as e:
        if "ConnectError" not in str(type(e)):
            _logger.error(f"Poll error: {e}")
            print(f"[task-puller] Error: {e}")


async def _sync_workspace_from_r2(client, worker_url, auth_key, session_id, workspace_dir):
    """Download workspace files from R2 to local workspace before execution.
    This enables cross-node context: files generated by other nodes are available locally.
    """
    try:
        resp = await client.get(
            f"{worker_url}/api/sessions/{session_id}/workspace",
            headers={"X-API-Key": auth_key},
            timeout=10,
        )
        if resp.status_code != 200:
            return
        files = resp.json().get("files", [])
        for f in files:
            if f["type"] != "file":
                continue
            local_path = os.path.join(workspace_dir, f["path"])
            if os.path.exists(local_path):
                continue  # Don't overwrite local files
            # Download file content
            try:
                read_resp = await client.get(
                    f"{worker_url}/api/sessions/{session_id}/workspace/read",
                    params={"path": f["path"]},
                    headers={"X-API-Key": auth_key},
                    timeout=15,
                )
                if read_resp.status_code == 200:
                    content = read_resp.json().get("content", "")
                    os.makedirs(os.path.dirname(local_path), exist_ok=True)
                    with open(local_path, "w") as fh:
                        fh.write(content)
                    _logger.info(f"SYNC ← R2: {f['path']} ({len(content)} chars)")
            except Exception:
                pass
    except Exception as e:
        _logger.debug(f"Workspace sync from R2 skipped: {e}")


async def _post_result(client, worker_url, auth_key, task_id, exit_code, result_text):
    """Post task result back to CF Worker callback endpoint."""
    try:
        resp1 = await client.post(
            f"{worker_url}/api/tasks/{task_id}/complete",
            json={"exitCode": exit_code, "resultText": result_text},
            headers={"X-API-Key": auth_key, "Content-Type": "application/json"},
            timeout=30,
        )
        _logger.info(f"CALLBACK {task_id[:12]} | tasks/complete → {resp1.status_code}")
        resp2 = await client.post(
            f"{worker_url}/api/nodes/task-complete/{task_id}",
            json={"exitCode": exit_code, "resultText": result_text},
            headers={"X-API-Key": auth_key, "Content-Type": "application/json"},
            timeout=10,
        )
        _logger.info(f"CALLBACK {task_id[:12]} | nodes/task-complete → {resp2.status_code}")
    except Exception as e:
        _logger.error(f"CALLBACK {task_id[:12]} | FAILED: {e}")
        print(f"[task-puller] Callback failed for {task_id[:8]}: {e}")


async def _poll_loop():
    """Continuously poll for tasks."""
    while True:
        try:
            await _pull_and_execute()
        except Exception as e:
            print(f"[task-puller] Poll error: {e}")
        await asyncio.sleep(POLL_INTERVAL)


def start_task_puller():
    """Start the background task puller."""
    global _puller_task
    _puller_task = asyncio.create_task(_poll_loop())
    print(f"[task-puller] Started (polling every {POLL_INTERVAL}s)")


def stop_task_puller():
    """Stop the task puller."""
    global _puller_task
    if _puller_task:
        _puller_task.cancel()
        _puller_task = None
